### ISSUE TITLE
Add ships 

### ISSUE THREAD

**Issue by TheDragonMeister** [OSU-CS361-W17/group22_project3#7]
Add Clipper (size: 3) and Dinghy (size: 1) ship types to the civilian ships.

**Comment by alfayeza** [comment]
I have added those while adding the two classes. However, the rest of the ships are still of type 'ship' instead of type 'military' (i.e. they're still related to the base class not the child)

**Comment by khaneh321** [comment]
I have changed the ship types to 'military'.
